### PR TITLE
fix(redirects): check for absolute URLs

### LINKED ISSUE #2230: Page Not Found error when opening the "Terraform Guides" link on one of our historic "Writing Custom Terraform Providers" blog.
Hi folks, 

Getting a Page Not Found error when opening the **"Terraform Guides"** link on the ["Writing Custom Terraform Providers" article](https://www.hashicorp.com/blog/writing-custom-terraform-providers) by Mitchell H.

Screen Shot 2022-04-06 at 5 12 00 PM

Noticed the page resolves to this incorrect URL: **`https://www.terraform.io/https:/learn.hashicorp.com/collections/terraform/providers`**

Should redirect to this instead: https://learn.hashicorp.com/collections/terraform/providers

Thanks!

### PR DESCRIPTION
**Pull request by BRKalow**
Correctly handle absolute URL redirect destinations, instead of appending them to the current domain.

* Navigate to: https://terraform-website-git-brkfix-middleware-redire-62e8ae-hashicorp.vercel.app/guides/writing-custom-terraform-providers.html
* Validate that you correctly get redirected to learn

closes #2230

### CODE REVIEW

File: pages/docs/_middleware.ts [hunk 1]
```diff
@@ -22,6 +22,14 @@ export function middleware(req: NextRequest, ev: NextFetchEvent) {
 
     for (const key of [path, pathIndexHtml, pathHtml]) {
       if (key in docsRedirects) {
+        const destination = doscRedirects[key]
```
Comment (BRKalow) [inline pages/docs/_middleware.ts:25]:
```suggestion
        const destination = docsRedirects[key]
```

File: pages/docs/_middleware.ts [hunk 2]
```diff
@@ -22,10 +22,18 @@ export function middleware(req: NextRequest, ev: NextFetchEvent) {
 
     for (const key of [path, pathIndexHtml, pathHtml]) {
       if (key in docsRedirects) {
+        const destination = docsRedirects[key]
+        
+        if (destination.startsWith('https://')) {
```
Comment (kylemac) [inline pages/docs/_middleware.ts:27]: do we need to check for `http` also?

Comment (BRKalow) [reply pages/docs/_middleware.ts:27]: There are not any `http://` redirects defined at the moment, and I wouldn't expect any new ones to get added going forward. I can add it for completeness though 👍

Comment (BRKalow) [inline pages/docs/_middleware.ts:27]:
```suggestion
        if (destination.startsWith('https://') || destination.startsWith('http://')) {
```

**Review by kylemac — APPROVED** [review]
